# Generated by Django 5.2.7 on 2025-11-19 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_solicitud_turno', models.BooleanField(default=True, help_text='Notificar cuando un cliente solicita un turno')),
                ('notificar_pago_turno', models.BooleanField(default=True, help_text='Notificar cuando un cliente paga un turno')),
                ('notificar_cancelacion_turno', models.BooleanField(default=True, help_text='Notificar cuando un cliente cancela un turno')),
                ('notificar_modificacion_turno', models.BooleanField(default=True, help_text='Notificar cuando se modifica un turno')),
                ('notificar_nuevo_empleado', models.BooleanField(default=True, help_text='Notificar cuando se registra un nuevo empleado (solo propietario)')),
                ('notificar_nuevo_cliente', models.BooleanField(default=True, help_text='Notificar cuando se registra un nuevo cliente (solo propietario)')),
                ('notificar_reporte_diario', models.BooleanField(default=True, help_text='Notificar resumen diario de turnos (solo propietario)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud_turno', 'Solicitud de Turno'), ('pago_turno', 'Pago de Turno'), ('cancelacion_turno', 'Cancelación de Turno'), ('modificacion_turno', 'Modificación de Turno'), ('nuevo_empleado', 'Nuevo Empleado'), ('nuevo_cliente', 'Nuevo Cliente'), ('reporte_diario', 'Reporte Diario'), ('recordatorio', 'Recordatorio')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leida_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='notificacio_usuario_15c13d_idx'), models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_2c9179_idx')],
            },
        ),
    ]
