# Generated by Django 5.2.7 on 2025-11-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionconfig',
            name='email_cancelacion_turno',
            field=models.BooleanField(default=True, help_text='Enviar email cuando se cancela un turno'),
        ),
        migrations.AddField(
            model_name='notificacionconfig',
            name='email_modificacion_turno',
            field=models.BooleanField(default=True, help_text='Enviar email cuando se modifica un turno'),
        ),
        migrations.AddField(
            model_name='notificacionconfig',
            name='email_pago_turno',
            field=models.BooleanField(default=True, help_text='Enviar email cuando hay pago pendiente'),
        ),
        migrations.AddField(
            model_name='notificacionconfig',
            name='email_recordatorio_turno',
            field=models.BooleanField(default=True, help_text='Enviar email recordatorio antes del turno'),
        ),
        migrations.AddField(
            model_name='notificacionconfig',
            name='email_reporte_diario',
            field=models.BooleanField(default=True, help_text='Enviar email con reporte diario (solo propietario)'),
        ),
        migrations.AddField(
            model_name='notificacionconfig',
            name='email_solicitud_turno',
            field=models.BooleanField(default=True, help_text='Enviar email cuando se asigna un turno'),
        ),
    ]
