# Generated by Django 4.2.16 on 2025-09-23 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No Asistió')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('notas_cliente', models.TextField(blank=True, null=True, verbose_name='Notas del cliente')),
                ('notas_empleado', models.TextField(blank=True, null=True, verbose_name='Notas del empleado')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='clientes.cliente', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='empleados.empleado', verbose_name='Empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción realizada')),
                ('estado_anterior', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado nuevo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='turnos.turno')),
            ],
            options={
                'verbose_name': 'Historial de Turno',
                'verbose_name_plural': 'Historiales de Turnos',
                'ordering': ['-created_at'],
            },
        ),
    ]
