# Generated by Django 5.2.8 on 2026-03-13 02:17

import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción realizada')),
                ('estado_anterior', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Estado nuevo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del cambio')),
            ],
            options={
                'verbose_name': 'Historial de Turno',
                'verbose_name_plural': 'Historiales de Turnos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTurno',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No Asistió'), ('oferta_enviada', 'Oferta enviada'), ('expirada', 'Expirada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('notas_cliente', models.TextField(blank=True, null=True, verbose_name='Notas del cliente')),
                ('notas_empleado', models.TextField(blank=True, null=True, verbose_name='Notas del empleado')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio final')),
                ('senia_pagada', models.DecimalField(decimal_places=2, default=0, help_text='Monto de seña ya abonada por el cliente', max_digits=10, verbose_name='Seña pagada')),
                ('fecha_hora_completado', models.DateTimeField(blank=True, help_text='Registra cuándo se marcó el turno como completado', null=True, verbose_name='Fecha y hora de finalización')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Turno',
                'verbose_name_plural': 'historical Turnos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LogReasignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de descuento')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('estado_final', models.CharField(blank=True, choices=[('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], max_length=20, null=True, verbose_name='Estado final')),
            ],
            options={
                'verbose_name': 'Log de Reasignación',
                'verbose_name_plural': 'Logs de Reasignación',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No Asistió'), ('oferta_enviada', 'Oferta enviada'), ('expirada', 'Expirada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('notas_cliente', models.TextField(blank=True, null=True, verbose_name='Notas del cliente')),
                ('notas_empleado', models.TextField(blank=True, null=True, verbose_name='Notas del empleado')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio final')),
                ('senia_pagada', models.DecimalField(decimal_places=2, default=0, help_text='Monto de seña ya abonada por el cliente', max_digits=10, verbose_name='Seña pagada')),
                ('fecha_hora_completado', models.DateTimeField(blank=True, help_text='Registra cuándo se marcó el turno como completado', null=True, verbose_name='Fecha y hora de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
