# Generated by Django 5.2.8 on 2026-03-13 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('empleados', '0002_initial'),
        ('servicios', '0002_initial'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialturno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='empleado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='sala',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicios.sala', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='servicio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='logreasignacion',
            name='cliente_notificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_notificadas', to='clientes.cliente', verbose_name='Cliente notificado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='servicios.sala', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='logreasignacion',
            name='turno_cancelado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasignaciones_cancelado', to='turnos.turno', verbose_name='Turno cancelado'),
        ),
        migrations.AddField(
            model_name='logreasignacion',
            name='turno_ofrecido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasignaciones_ofrecido', to='turnos.turno', verbose_name='Turno ofrecido'),
        ),
        migrations.AddField(
            model_name='historialturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='turnos.turno'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('empleado', 'fecha_hora')},
        ),
        migrations.AddIndex(
            model_name='logreasignacion',
            index=models.Index(fields=['token'], name='turnos_logr_token_346711_idx'),
        ),
        migrations.AddIndex(
            model_name='logreasignacion',
            index=models.Index(fields=['estado_final', '-fecha_envio'], name='turnos_logr_estado__e359e4_idx'),
        ),
    ]
