# Generated by Django 4.2.16 on 2025-09-23 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialturno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('empleado', 'fecha_hora')},
        ),
    ]
