# Generated by Django 5.2.8 on 2026-01-24 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('empleados', '0002_initial'),
        ('servicios', '0001_initial'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialturno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio'),
        ),
        migrations.AddField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='historialturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='turnos.turno'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('empleado', 'fecha_hora')},
        ),
    ]
