# Generated by Django 5.2.8 on 2026-03-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_is_active_historicalcliente_is_active'),
        ('empleados', '0004_empleado_is_active_alter_empleadoservicio_empleado_and_more'),
        ('servicios', '0003_historicalservicio_descuento_fidelizacion_monto_and_more'),
        ('turnos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='turnos.turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='empleados.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='servicios.servicio', verbose_name='Servicio'),
        ),
    ]
