# Generated by Django 5.2.7 on 2025-11-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_hora_completado',
            field=models.DateTimeField(blank=True, help_text='Registra cuándo se marcó el turno como completado', null=True, verbose_name='Fecha y hora de finalización'),
        ),
    ]
