# Generated by Django 5.2.8 on 2026-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_historialturno_turno_alter_turno_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturno',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo ingresado por el cliente o el staff al cancelar el turno.', null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='turno',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Motivo ingresado por el cliente o el staff al cancelar el turno.', null=True, verbose_name='Motivo de cancelación'),
        ),
    ]
