# Generated by Django 5.2.7 on 2025-11-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_turno_fecha_hora_completado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_hora_cancelado',
            field=models.DateTimeField(blank=True, help_text='Registra cuándo se canceló el turno', null=True, verbose_name='Fecha y hora de cancelación'),
        ),
        migrations.AddField(
            model_name='turno',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Razón por la cual se canceló el turno', null=True, verbose_name='Motivo de cancelación'),
        ),
    ]
