# Generated by Django 5.2.8 on 2026-02-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_reasignacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logreasignacion',
            new_name='turnos_logr_token_346711_idx',
            old_name='turnos_logre_token_4d857a_idx',
        ),
        migrations.RenameIndex(
            model_name='logreasignacion',
            new_name='turnos_logr_estado__e359e4_idx',
            old_name='turnos_logre_estado__15b8f3_idx',
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No Asistió'), ('oferta_enviada', 'Oferta enviada'), ('expirada', 'Expirada')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
