# Generated by Django 5.2.8 on 2026-03-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_historicalturno_motivo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturno',
            name='canal_reserva',
            field=models.CharField(blank=True, choices=[('web_cliente', 'Web cliente'), ('panel_profesional', 'Panel profesional'), ('panel_propietario', 'Panel propietario')], help_text='Origen del turno (web cliente, panel profesional, panel propietario)', max_length=30, null=True, verbose_name='Canal de reserva'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='es_cliente_registrado',
            field=models.BooleanField(default=True, help_text='Indica si el cliente ya existía en la base al crear el turno', verbose_name='Cliente ya registrado'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='fecha_pago_registrado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de registro de pago'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('mercadopago', 'Mercado Pago'), ('mercadopago_qr', 'Mercado Pago QR'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], help_text='Método de pago utilizado para la seña o el pago total', max_length=30, null=True, verbose_name='Método de pago principal'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='walkin_dni',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='DNI cliente walk-in'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='walkin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email cliente walk-in'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='walkin_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre cliente walk-in'),
        ),
        migrations.AddField(
            model_name='historicalturno',
            name='walkin_telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono cliente walk-in'),
        ),
        migrations.AddField(
            model_name='turno',
            name='canal_reserva',
            field=models.CharField(blank=True, choices=[('web_cliente', 'Web cliente'), ('panel_profesional', 'Panel profesional'), ('panel_propietario', 'Panel propietario')], help_text='Origen del turno (web cliente, panel profesional, panel propietario)', max_length=30, null=True, verbose_name='Canal de reserva'),
        ),
        migrations.AddField(
            model_name='turno',
            name='es_cliente_registrado',
            field=models.BooleanField(default=True, help_text='Indica si el cliente ya existía en la base al crear el turno', verbose_name='Cliente ya registrado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_pago_registrado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de registro de pago'),
        ),
        migrations.AddField(
            model_name='turno',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('mercadopago', 'Mercado Pago'), ('mercadopago_qr', 'Mercado Pago QR'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('mixto', 'Mixto')], help_text='Método de pago utilizado para la seña o el pago total', max_length=30, null=True, verbose_name='Método de pago principal'),
        ),
        migrations.AddField(
            model_name='turno',
            name='walkin_dni',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='DNI cliente walk-in'),
        ),
        migrations.AddField(
            model_name='turno',
            name='walkin_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email cliente walk-in'),
        ),
        migrations.AddField(
            model_name='turno',
            name='walkin_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre cliente walk-in'),
        ),
        migrations.AddField(
            model_name='turno',
            name='walkin_telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono cliente walk-in'),
        ),
    ]
