# Generated by Django 5.2.7 on 2025-11-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_turno_fecha_hora_cancelado_turno_motivo_cancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_hora_confirmado',
            field=models.DateTimeField(blank=True, help_text='Registra cuándo se confirmó el turno', null=True, verbose_name='Fecha y hora de confirmación'),
        ),
    ]
