# Generated by Django 5.2.8 on 2026-02-07 23:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_historicalcliente'),
        ('empleados', '0002_initial'),
        ('servicios', '0004_historicalservicio'),
        ('turnos', '0004_rename_turnos_logre_token_4d857a_idx_turnos_logr_token_346711_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTurno',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No Asistió'), ('oferta_enviada', 'Oferta enviada'), ('expirada', 'Expirada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('notas_cliente', models.TextField(blank=True, null=True, verbose_name='Notas del cliente')),
                ('notas_empleado', models.TextField(blank=True, null=True, verbose_name='Notas del empleado')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio final')),
                ('senia_pagada', models.DecimalField(decimal_places=2, default=0, help_text='Monto de seña ya abonada por el cliente', max_digits=10, verbose_name='Seña pagada')),
                ('fecha_hora_completado', models.DateTimeField(blank=True, help_text='Registra cuándo se marcó el turno como completado', null=True, verbose_name='Fecha y hora de finalización')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='empleados.empleado', verbose_name='Empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicios.servicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'historical Turno',
                'verbose_name_plural': 'historical Turnos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
