# Generated by Django 5.2.8 on 2026-03-18 19:50

from decimal import Decimal
from django.db import migrations, models


def _backfill_tipo_pago_turno(apps, schema_editor):
    Turno = apps.get_model("turnos", "Turno")

    for turno in Turno.objects.select_related("servicio").all().iterator():
        senia_pagada = Decimal(turno.senia_pagada or 0)
        precio_base = Decimal(
            turno.precio_final or (turno.servicio.precio if turno.servicio else 0) or 0
        )

        if senia_pagada <= Decimal("0.00"):
            tipo_pago = "SIN_PAGO"
        elif precio_base > Decimal("0.00") and senia_pagada >= precio_base:
            tipo_pago = "PAGO_COMPLETO"
        else:
            tipo_pago = "SENIA"

        turno.tipo_pago = tipo_pago
        turno.save(update_fields=["tipo_pago"])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0005_historicalturno_canal_reserva_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalturno",
            name="tipo_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIN_PAGO", "Sin pago"),
                    ("SENIA", "Seña"),
                    ("PAGO_COMPLETO", "Pago completo"),
                ],
                help_text="Indica si el turno fue abonado con seña o pago completo.",
                max_length=20,
                null=True,
                verbose_name="Tipo de pago",
            ),
        ),
        migrations.AddField(
            model_name="logreasignacion",
            name="regla_descuento_aplicada",
            field=models.CharField(
                blank=True,
                max_length=80,
                null=True,
                verbose_name="Regla de descuento aplicada",
            ),
        ),
        migrations.AddField(
            model_name="logreasignacion",
            name="tipo_pago_cliente_ofertado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIN_PAGO", "Sin pago"),
                    ("SENIA", "Seña"),
                    ("PAGO_COMPLETO", "Pago completo"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de pago del cliente ofertado",
            ),
        ),
        migrations.AddField(
            model_name="turno",
            name="tipo_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SIN_PAGO", "Sin pago"),
                    ("SENIA", "Seña"),
                    ("PAGO_COMPLETO", "Pago completo"),
                ],
                help_text="Indica si el turno fue abonado con seña o pago completo.",
                max_length=20,
                null=True,
                verbose_name="Tipo de pago",
            ),
        ),
        migrations.RunPython(_backfill_tipo_pago_turno, _noop_reverse),
    ]
