# Generated by Django 5.2.8 on 2026-02-23 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_historicalsala_sala'),
        ('turnos', '0005_historicalturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalturno',
            name='sala',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicios.sala', verbose_name='Sala'),
        ),
        migrations.AddField(
            model_name='turno',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='servicios.sala', verbose_name='Sala'),
        ),
    ]
