# Generated by Django 5.2.7 on 2025-11-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_turno_fecha_hora_confirmado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha_hora_cancelado',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_hora_confirmado',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='motivo_cancelacion',
        ),
    ]
