# Generated by Django 5.2.7 on 2025-11-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_remove_turno_fecha_hora_cancelado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
    ]
