# Generated by Django 5.2.7 on 2025-11-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_promedio_calificacion_and_more'),
        ('turnos', '0007_remove_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('empleado', 'fecha_hora')},
        ),
    ]
