# Generated by Django 5.2.8 on 2026-04-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_solicitud_reprogramacion_flexible'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicitudreprogramacionflexible',
            new_name='turnos_soli_estado_2c3338_idx',
            old_name='turnos_sol_estado_d0f2a5_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitudreprogramacionflexible',
            new_name='turnos_soli_turno_i_414283_idx',
            old_name='turnos_sol_turno_e0bcd9_idx',
        ),
    ]
