# Generated by Django 5.2.8 on 2026-04-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_turno_pendiente_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalturno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No Asistió'), ('pendiente_manual', 'Pendiente manual'), ('oferta_enviada', 'Oferta enviada'), ('expirada', 'Expirada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No Asistió'), ('pendiente_manual', 'Pendiente manual'), ('oferta_enviada', 'Oferta enviada'), ('expirada', 'Expirada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
