# Generated by Django 5.2.8 on 2026-04-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_alter_historicalturno_estado_alter_turno_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
    ]
