# Generated by Django 5.2.8 on 2026-05-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0015_streakcoupon'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='streakcoupon',
            new_name='turnos_stre_cliente_951c1d_idx',
            old_name='turnos_stre_cliente_7c87a9_idx',
        ),
        migrations.RenameIndex(
            model_name='streakcoupon',
            new_name='turnos_stre_code_84890f_idx',
            old_name='turnos_stre_code_16d4d8_idx',
        ),
    ]
