# Generated by Django 5.2.8 on 2026-05-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0017_merge_0016_migrations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='logreasignacion',
            new_name='turnos_logr_cliente_920ad3_idx',
            old_name='turnos_logr_cliente_45d8a1_idx',
        ),
        migrations.AlterField(
            model_name='historicalturno',
            name='canal_reserva',
            field=models.CharField(blank=True, choices=[('web_cliente', 'Web cliente'), ('fidelizacion', 'Oferta de fidelización'), ('panel_profesional', 'Panel profesional'), ('panel_propietario', 'Panel propietario')], help_text='Origen del turno (web cliente, panel profesional, panel propietario)', max_length=30, null=True, verbose_name='Canal de reserva'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='canal_reserva',
            field=models.CharField(blank=True, choices=[('web_cliente', 'Web cliente'), ('fidelizacion', 'Oferta de fidelización'), ('panel_profesional', 'Panel profesional'), ('panel_propietario', 'Panel propietario')], help_text='Origen del turno (web cliente, panel profesional, panel propietario)', max_length=30, null=True, verbose_name='Canal de reserva'),
        ),
    ]
