# Generated by Django 5.2.8 on 2026-06-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0019_movimientopagoturno'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movimientopagoturno',
            new_name='turnos_movi_turno_i_0982a8_idx',
            old_name='turnos_movi_turno_i_0c94a8_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientopagoturno',
            new_name='turnos_movi_referen_ec5ab5_idx',
            old_name='turnos_movi_referen_b85bb0_idx',
        ),
    ]
