"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from environ import Env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MERCADO_PAAGO_WEBHOOK_URL = env(
    "MERCADO_PAGO_WEBHOOK_URL",
    default="https://subarticulately-strifeless-eliza.ngrok-free.dev/api/mercadopago/webhook/",
)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default=("django-insecure-_43q(bfy+%%qe4!=2wq=3k4ay(j8pg8smoa$1zl(" "14q^6$@+jy"),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1",
    cast=lambda v: [s.strip() for s in v.split(",")],
)

# En desarrollo, permitir cualquier host (cubre tunnels como ngrok)
if DEBUG:
    ALLOWED_HOSTS = ["*"]

# Confiar en los headers de proxy (ngrok, nginx, etc.) para obtener el host/scheme reales.
# Sin esto, Django construye URLs con http://localhost:8000 en lugar de la URL pública.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    "jet.dashboard",
    "jet",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third party apps
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    "social_django",  # Google OAuth
    "simple_history",
    # Local apps
    "apps.authentication",
    "apps.users",
    "apps.turnos",
    "apps.servicios",
    "apps.clientes",
    "apps.empleados",
    "apps.encuestas",
    "apps.emails",
    "apps.mercadopago",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME", default="db_proyecto"),
        "USER": config("DB_USER", default="user_admin"),
        "PASSWORD": config("DB_PASSWORD", default="password_seguro"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5433"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "MinimumLengthValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation." "NumericPasswordValidator"),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "es-ar"

TIME_ZONE = "America/Argentina/Buenos_Aires"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Solo TokenAuthentication: el frontend usa Token en el header Authorization.
        # SessionAuthentication fue eliminado porque fuerza validación CSRF en todos
        # los endpoints POST, lo cual rompe la API cuando se consume desde Next.js.
        # El admin de Django usa su propio sistema de sesiones y no depende de esto.
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_PAGINATION_CLASS": ("rest_framework.pagination.PageNumberPagination"),
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://subarticulately-strifeless-eliza.ngrok-free.dev",
]

CORS_ALLOW_CREDENTIALS = True

# Requerido para que el middleware CSRF acepte peticiones desde el frontend
# (el browser envía Origin: http://localhost:3000 cuando el proxy de Next.js
# reenvía la petición, y Django lo valida contra esta lista)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "https://subarticulately-strifeless-eliza.ngrok-free.dev",
]

# Headers adicionales permitidos en CORS
CORS_ALLOWED_HEADERS = [
    "Accept",
    "ngrok-skip-browser-warning",
    "accept-encoding",
    "authorization",
    "Content-Type",
    "dnt",
    "origin",
    "cache-control",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOWED_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
# Static files configuration
STATIC_ROOT = BASE_DIR / "staticfiles"

# Usar WhiteNoise solo en producción, Django estándar en desarrollo
if DEBUG:
    # En desarrollo, usar el sistema estándar de Django para mejor compatibilidad con Jet
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    # En producción, usar WhiteNoise con compresión
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Custom User Model
AUTH_USER_MODEL = "users.User"

# Authentication Backends - Usar email para login + Google OAuth
AUTHENTICATION_BACKENDS = [
    "apps.authentication.backends.CustomGoogleOAuth2",  # Google OAuth2 personalizado (usa BD)
    "apps.users.backends.EmailBackend",  # Backend personalizado para email
    "django.contrib.auth.backends.ModelBackend",  # Fallback al backend por defecto
]

# ============================================================================
# GOOGLE OAUTH CONFIGURATION
# ============================================================================
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config("GOOGLE_OAUTH2_CLIENT_ID", default="")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config("GOOGLE_OAUTH2_CLIENT_SECRET", default="")

# Redirect URI: Google llama a este endpoint después de autorizar al usuario.
# En desarrollo con ngrok, sobreescribir con GOOGLE_OAUTH2_REDIRECT_URI en el .env.
# El path real de social-auth-app-django es /api/auth/complete/google-oauth2/
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = config(
    "GOOGLE_OAUTH2_REDIRECT_URI",
    default="http://localhost:8000/api/auth/complete/google-oauth2/",
)

# Scope de Google OAuth (qué permisos solicitar)
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    "https://www.googleapis.com/auth/userinfo.email",
    "https://www.googleapis.com/auth/userinfo.profile",
]

# Usuario activo por defecto
SOCIAL_AUTH_GOOGLE_OAUTH2_USER_FIELDS = ["email", "first_name", "last_name"]

# Pipeline personalizado para crear usuarios con rol Cliente
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "apps.authentication.pipeline.associate_by_email",  # Asociar por email si el usuario ya existe
    "social_core.pipeline.user.get_username",
    "apps.authentication.pipeline.create_user_with_username",  # Pipeline personalizado para generar username
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "apps.authentication.pipeline.create_cliente_profile",  # Pipeline personalizado para crear perfil Cliente
    "apps.authentication.pipeline.redirect_with_token",  # Redirigir al frontend con el token
)

# Configuración adicional de social auth
SOCIAL_AUTH_URL_NAMESPACE = "social"
SOCIAL_AUTH_LOGIN_REDIRECT_URL = (
    config("FRONTEND_URL", default="http://localhost:3000") + "/auth/callback"
)
SOCIAL_AUTH_LOGIN_ERROR_URL = (
    config("FRONTEND_URL", default="http://localhost:3000") + "/login?error=oauth"
)
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = ["username", "first_name", "last_name", "email"]


# Django JET Configuration
JET_DEFAULT_THEME = "light-blue"
JET_SIDE_MENU_COMPACT = True
JET_CHANGE_FORM_SIBLING_LINKS = True

JET_THEMES = [
    {"theme": "default", "color": "#47bac1", "title": "Cyan (Default)"},
    {"theme": "green", "color": "#44b78b", "title": "Verde Esmeralda"},
    {"theme": "light-green", "color": "#2faa60", "title": "Verde Claro"},
    {"theme": "light-violet", "color": "#a464c4", "title": "Violeta"},
    {"theme": "light-blue", "color": "#5EADDE", "title": "Azul Cielo"},
    {"theme": "light-gray", "color": "#222", "title": "Gris Oscuro"},
]

# settings.py modificado para Mailpit (Local)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("EMAIL_HOST", default="127.0.0.1")
EMAIL_PORT = config("EMAIL_PORT", default=1025, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=False, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL", default="Beautiful Studio <noreply@beautifulstudio.com>"
)

# ============================================================================
# CELERY CONFIGURATION
# ============================================================================
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "America/Argentina/Buenos_Aires"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos máximo por tarea
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# Configuración de Celery Beat (tareas periódicas)
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Frontend URL for email links
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")

# ── Mercado Pago ─────────────────────────────────────────────────────────────
MP_ACCESS_TOKEN = config("MP_ACCESS_TOKEN", default="")
MP_PUBLIC_KEY = config("MP_PUBLIC_KEY", default="")
MP_CURRENCY_ID = config("MP_CURRENCY_ID", default="ARS")

MERCADO_PAGO_WEBHOOK_URL = env(
    "MERCADO_PAGO_WEBHOOK_URL",
    default="https://subarticulately-strifeless-eliza.ngrok-free.dev/api/mercadopago/webhook/",
)
# URLs de retorno
MERCADO_PAGO_SUCCESS_URL = env(
    "MERCADO_PAGO_SUCCESS_URL", default="http://localhost:3000/pago-exitoso"
)
MERCADO_PAGO_FAILURE_URL = env(
    "MERCADO_PAGO_FAILURE_URL", default="http://localhost:3000/pago-fallido"
)
MERCADO_PAGO_PENDING_URL = env(
    "MERCADO_PAGO_PENDING_URL", default="http://localhost:3000/pago-pendiente"
)  # Monto mínimo permitido por Mercado Pago (en ARS). MP rechaza montos menores.
MP_MIN_AMOUNT = config("MP_MIN_AMOUNT", default=100, cast=float)
# ──────────────────────────────────────────────────────────────────────────────
# Logging
# ──────────────────────────────────────────────────────────────────────────────
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        # Muestra INFO+ para las apps propias (incluye webhook MP, mercadopago, etc.)
        "apps": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
