[tool.pylint.messages_control]
# Lista de advertencias a desactivar.
# C0114: missing-module-docstring
# C0115: missing-class-docstring
# C0116: missing-function-docstring
# C0301: line-too-long
# C0303: trailing-whitespace
# C0304: missing-final-newline
disable = [
    "C0114",
    "C0115",
    "C0116",
    "C0301",
    "C0303",
    "C0304",
]