# Generated by Django 4.2.16 on 2025-10-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('cliente', 'Cliente'), ('profesional', 'Profesional'), ('propietario', 'Propietario'), ('superusuario', 'Superusuario')], default='cliente', max_length=15, verbose_name='Rol'),
        ),
    ]
