# Generated by Django 4.2.16 on 2025-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad o equivalente', max_length=20, null=True, unique=True, verbose_name='DNI/Documento'),
        ),
    ]
