# Generated by Django 5.2.7 on 2025-11-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('propietario', 'Propietario'), ('profesional', 'Profesional'), ('cliente', 'Cliente'), ('superusuario', 'Superusuario')], default='cliente', max_length=15, verbose_name='Rol'),
        ),
    ]
