# Generated by Django 5.2.8 on 2026-03-13 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('solicitud_turno', 'Solicitud de Turno'), ('pago_turno', 'Pago de Turno'), ('cancelacion_turno', 'Cancelación de Turno'), ('modificacion_turno', 'Modificación de Turno'), ('nuevo_empleado', 'Nuevo Empleado'), ('nuevo_cliente', 'Nuevo Cliente'), ('reporte_diario', 'Reporte Diario'), ('recordatorio', 'Recordatorio'), ('fidelizacion', 'Fidelización de Clientes')], max_length=50),
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_accion', models.CharField(choices=[('CON_SALDO', 'Con saldo en billetera'), ('CON_DESCUENTO', 'Con descuento')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Acceso',
                'verbose_name_plural': 'Tokens de Acceso',
                'db_table': 'emails_accesstoken',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='emails_acce_token_1c52f0_idx'), models.Index(fields=['user', '-created_at'], name='emails_acce_user_id_b4ed6b_idx')],
            },
        ),
    ]
