# Generated by Django 5.2.8 on 2026-02-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_passwordresettoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=150, unique=True, verbose_name='Token'),
        ),
    ]
