# Generated by Django 5.2.8 on 2026-02-07 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='notificacio_usuario_15c13d_idx',
            old_name='emails_noti_usuario_6e59ee_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacion',
            new_name='notificacio_usuario_2c9179_idx',
            old_name='emails_noti_usuario_888b9f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='notificacio_token_59e51c_idx',
            old_name='emails_pass_token_d4a529_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='notificacio_user_id_7c22a2_idx',
            old_name='emails_pass_user_id_d74c3a_idx',
        ),
        migrations.AlterModelTable(
            name='notificacion',
            table='notificaciones_notificacion',
        ),
        migrations.AlterModelTable(
            name='notificacionconfig',
            table='notificaciones_notificacionconfig',
        ),
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='notificaciones_passwordresettoken',
        ),
    ]
