# Generated by Django 5.2.8 on 2026-06-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_promotionoffer_reacomodamiento'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotionoffer',
            new_name='emails_prom_token_d3dd86_idx',
            old_name='emails_prom_token_914ebe_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionoffer',
            new_name='emails_prom_campaig_beb885_idx',
            old_name='emails_prom_campaig_9396b5_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionoffer',
            new_name='emails_prom_process_27e3e9_idx',
            old_name='emails_prom_process_f44750_idx',
        ),
        migrations.RenameIndex(
            model_name='promotionoffer',
            new_name='emails_prom_cliente_53f105_idx',
            old_name='emails_prom_cliente_fa2221_idx',
        ),
    ]
