# Generated by Django 4.2.16 on 2025-09-29 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_dato', models.CharField(choices=[('str', 'Texto'), ('int', 'Entero'), ('float', 'Decimal'), ('bool', 'Booleano'), ('json', 'JSON')], default='str', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='PermisoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ver_reportes', 'Ver Reportes'), ('gestionar_precios', 'Gestionar Precios'), ('gestionar_horarios', 'Gestionar Horarios'), ('ver_todos_turnos', 'Ver Todos los Turnos'), ('cancelar_turnos', 'Cancelar Turnos'), ('gestionar_promociones', 'Gestionar Promociones'), ('acceso_caja', 'Acceso a Caja'), ('gestionar_inventario', 'Gestionar Inventario')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='permisos_adicionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso Adicional',
                'verbose_name_plural': 'Permisos Adicionales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('cambio_password', 'Cambio de Contraseña'), ('cambio_rol', 'Cambio de Rol'), ('backup', 'Backup'), ('restaurar', 'Restaurar')], max_length=20)),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Acción',
                'verbose_name_plural': 'Auditoría de Acciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
