# Generated by Django 5.2.8 on 2026-03-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('cambio_password', 'Cambio de Contraseña'), ('cambio_rol', 'Cambio de Rol'), ('backup', 'Backup'), ('restaurar', 'Restaurar'), ('solicitar_reset_password', 'Solicitar Reset Password'), ('reset_password', 'Reset Password')], max_length=50)),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Acción',
                'verbose_name_plural': 'Auditoría de Acciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_dato', models.CharField(choices=[('str', 'Texto'), ('int', 'Entero'), ('float', 'Decimal'), ('bool', 'Booleano'), ('json', 'JSON')], default='str', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_horas_cancelacion_credito', models.IntegerField(default=24, help_text='Horas de antelación requeridas para que una cancelación genere crédito en billetera', verbose_name='Horas mínimas de antelación para crédito')),
                ('margen_fidelizacion_dias', models.IntegerField(default=60, help_text='Días promedio de inactividad antes de considerar al cliente para campañas de fidelización', verbose_name='Días de inactividad para reincorporación')),
                ('descuento_fidelizacion_pct', models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de descuento a aplicar en ofertas de reincorporación (ej: 15.00 para 15%)', max_digits=5, verbose_name='Porcentaje de descuento para fidelización')),
                ('capacidad_maxima_global', models.IntegerField(default=0, help_text='Límite total de turnos simultáneos en todo el local (0 = sin límite, usa solo capacidad de salas)', verbose_name='Capacidad máxima global del local')),
                ('nombre_empresa', models.CharField(blank=True, help_text='Nombre de empresa para comprobantes y datos fiscales', max_length=255, verbose_name='Nombre de empresa')),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre de fantasia del estudio o negocio', max_length=255, verbose_name='Nombre comercial')),
                ('razon_social', models.CharField(blank=True, help_text='Razon social registrada ante AFIP u organismo fiscal', max_length=255, verbose_name='Razon social')),
                ('cuit', models.CharField(blank=True, help_text='Numero de CUIT o identificador fiscal del negocio', max_length=20, verbose_name='CUIT / Identificador fiscal')),
                ('fecha_fundacion', models.DateField(blank=True, help_text='Fecha de inicio de actividades del negocio', null=True, verbose_name='Fecha de fundacion')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sso_activo', models.BooleanField(default=True, help_text='Activar/desactivar inicio de sesión con Google', verbose_name='Google SSO Activo')),
                ('autocreacion_cliente_sso', models.BooleanField(default=True, help_text='Crear automáticamente perfil de Cliente para usuarios que se registren con Google', verbose_name='Auto-creación de Cliente SSO')),
                ('client_id', models.CharField(blank=True, help_text='Client ID de Google Cloud Console', max_length=255, null=True, verbose_name='Google Client ID')),
                ('client_secret', models.CharField(blank=True, help_text='Client Secret de Google Cloud Console', max_length=255, null=True, verbose_name='Google Client Secret')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SSO',
                'verbose_name_plural': 'Configuración SSO',
            },
        ),
        migrations.CreateModel(
            name='PermisoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ver_reportes', 'Ver Reportes'), ('gestionar_precios', 'Gestionar Precios'), ('gestionar_horarios', 'Gestionar Horarios'), ('ver_todos_turnos', 'Ver Todos los Turnos'), ('cancelar_turnos', 'Cancelar Turnos'), ('gestionar_promociones', 'Gestionar Promociones'), ('acceso_caja', 'Acceso a Caja'), ('gestionar_inventario', 'Gestionar Inventario')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso Adicional',
                'verbose_name_plural': 'Permisos Adicionales',
                'ordering': ['nombre'],
            },
        ),
    ]
