# Generated by Django 5.2.8 on 2026-01-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('cambio_password', 'Cambio de Contraseña'), ('cambio_rol', 'Cambio de Rol'), ('backup', 'Backup'), ('restaurar', 'Restaurar')], max_length=20)),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Acción',
                'verbose_name_plural': 'Auditoría de Acciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_dato', models.CharField(choices=[('str', 'Texto'), ('int', 'Entero'), ('float', 'Decimal'), ('bool', 'Booleano'), ('json', 'JSON')], default='str', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sso_activo', models.BooleanField(default=True, help_text='Activar/desactivar inicio de sesión con Google', verbose_name='Google SSO Activo')),
                ('autocreacion_cliente_sso', models.BooleanField(default=True, help_text='Crear automáticamente perfil de Cliente para usuarios que se registren con Google', verbose_name='Auto-creación de Cliente SSO')),
                ('client_id', models.CharField(blank=True, help_text='Client ID de Google Cloud Console', max_length=255, null=True, verbose_name='Google Client ID')),
                ('client_secret', models.CharField(blank=True, help_text='Client Secret de Google Cloud Console', max_length=255, null=True, verbose_name='Google Client Secret')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SSO',
                'verbose_name_plural': 'Configuración SSO',
            },
        ),
        migrations.CreateModel(
            name='PermisoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('ver_reportes', 'Ver Reportes'), ('gestionar_precios', 'Gestionar Precios'), ('gestionar_horarios', 'Gestionar Horarios'), ('ver_todos_turnos', 'Ver Todos los Turnos'), ('cancelar_turnos', 'Cancelar Turnos'), ('gestionar_promociones', 'Gestionar Promociones'), ('acceso_caja', 'Acceso a Caja'), ('gestionar_inventario', 'Gestionar Inventario')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso Adicional',
                'verbose_name_plural': 'Permisos Adicionales',
                'ordering': ['nombre'],
            },
        ),
    ]
