# Generated by Django 5.2.7 on 2025-11-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sso_activo', models.BooleanField(default=True, help_text='Habilitar inicio de sesión con Google', verbose_name='Google SSO Activo')),
                ('autocreacion_cliente_sso', models.BooleanField(default=True, help_text='Crear automáticamente perfil de cliente al registrarse vía SSO', verbose_name='Autocrear Cliente en SSO')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SSO',
                'verbose_name_plural': 'Configuración SSO',
            },
        ),
    ]
