# Generated by Django 5.2.8 on 2026-01-24 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaacciones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permisoadicional',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='permisos_adicionales', to=settings.AUTH_USER_MODEL),
        ),
    ]
