# Generated by Django 5.2.7 on 2025-12-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_configuracionsso'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsso',
            name='client_id',
            field=models.CharField(blank=True, help_text='Client ID de Google Cloud Console', max_length=255, null=True, verbose_name='Google Client ID'),
        ),
        migrations.AddField(
            model_name='configuracionsso',
            name='client_secret',
            field=models.CharField(blank=True, help_text='Client Secret de Google Cloud Console', max_length=255, null=True, verbose_name='Google Client Secret'),
        ),
        migrations.AlterField(
            model_name='configuracionsso',
            name='autocreacion_cliente_sso',
            field=models.BooleanField(default=True, help_text='Crear automáticamente perfil de Cliente para usuarios que se registren con Google', verbose_name='Auto-creación de Cliente SSO'),
        ),
        migrations.AlterField(
            model_name='configuracionsso',
            name='google_sso_activo',
            field=models.BooleanField(default=True, help_text='Activar/desactivar inicio de sesión con Google', verbose_name='Google SSO Activo'),
        ),
    ]
