# Generated by Django 5.2.8 on 2026-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaacciones',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('cambio_password', 'Cambio de Contraseña'), ('cambio_rol', 'Cambio de Rol'), ('backup', 'Backup'), ('restaurar', 'Restaurar'), ('solicitar_reset_password', 'Solicitar Reset Password'), ('reset_password', 'Reset Password')], max_length=50),
        ),
    ]
