# Generated by Django 5.2.8 on 2026-02-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20260205_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_horas_cancelacion_credito', models.IntegerField(default=24, help_text='Horas de antelación requeridas para que una cancelación genere crédito en billetera', verbose_name='Horas mínimas de antelación para crédito')),
                ('margen_fidelizacion_dias', models.IntegerField(default=60, help_text='Días promedio de inactividad antes de considerar al cliente para campañas de fidelización', verbose_name='Días de inactividad para reincorporación')),
                ('descuento_fidelizacion_pct', models.DecimalField(decimal_places=2, default=15.0, help_text='Porcentaje de descuento a aplicar en ofertas de reincorporación (ej: 15.00 para 15%)', max_digits=5, verbose_name='Porcentaje de descuento para fidelización')),
                ('capacidad_maxima_global', models.IntegerField(default=0, help_text='Límite total de turnos simultáneos en todo el local (0 = sin límite, usa solo capacidad de salas)', verbose_name='Capacidad máxima global del local')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
    ]
