# Generated by Django 5.2.8 on 2026-05-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_configuracionglobal_streak_coupon_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionglobal',
            name='streak_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo de descuento promocional que se otorga al alcanzar la meta de racha.', max_digits=10, verbose_name='Bono fijo por racha'),
        ),
    ]
