# Generated by Django 5.2.8 on 2026-03-13 02:17

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSala',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('capacidad_simultanea', models.PositiveIntegerField(default=1, verbose_name='Capacidad simultánea')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Sala',
                'verbose_name_plural': 'historical Salas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServicio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descuento_reasignacion', models.DecimalField(decimal_places=2, default=0, help_text='Descuento fijo a aplicar cuando se ofrece un adelanto de turno', max_digits=10, verbose_name='Descuento por reasignación')),
                ('permite_reacomodamiento', models.BooleanField(default=False, help_text='Indica si el servicio participa en la lógica de rellenar huecos', verbose_name='Permite reacomodamiento')),
                ('tipo_descuento_adelanto', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto fijo')], default='PORCENTAJE', max_length=20, verbose_name='Tipo de descuento por adelanto')),
                ('valor_descuento_adelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor del descuento por adelanto')),
                ('tiempo_espera_respuesta', models.PositiveIntegerField(default=15, help_text='Minutos que el sistema espera antes de pasar al siguiente cliente', verbose_name='Tiempo de espera de respuesta (minutos)')),
                ('porcentaje_sena', models.DecimalField(decimal_places=2, default=25.0, help_text='Porcentaje que se cobrará por Mercado Pago', max_digits=5, verbose_name='Porcentaje de seña')),
                ('frecuencia_recurrencia_dias', models.PositiveIntegerField(default=30, help_text='Días sugeridos entre visitas. Usado para identificar clientes inactivos. Si es 0, usa la configuración global.', verbose_name='Frecuencia de retorno sugerida (días)')),
                ('duracion_minutos', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Servicio',
                'verbose_name_plural': 'historical Servicios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('capacidad_simultanea', models.PositiveIntegerField(default=1, verbose_name='Capacidad simultánea')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descuento_reasignacion', models.DecimalField(decimal_places=2, default=0, help_text='Descuento fijo a aplicar cuando se ofrece un adelanto de turno', max_digits=10, verbose_name='Descuento por reasignación')),
                ('permite_reacomodamiento', models.BooleanField(default=False, help_text='Indica si el servicio participa en la lógica de rellenar huecos', verbose_name='Permite reacomodamiento')),
                ('tipo_descuento_adelanto', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto fijo')], default='PORCENTAJE', max_length=20, verbose_name='Tipo de descuento por adelanto')),
                ('valor_descuento_adelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor del descuento por adelanto')),
                ('tiempo_espera_respuesta', models.PositiveIntegerField(default=15, help_text='Minutos que el sistema espera antes de pasar al siguiente cliente', verbose_name='Tiempo de espera de respuesta (minutos)')),
                ('porcentaje_sena', models.DecimalField(decimal_places=2, default=25.0, help_text='Porcentaje que se cobrará por Mercado Pago', max_digits=5, verbose_name='Porcentaje de seña')),
                ('frecuencia_recurrencia_dias', models.PositiveIntegerField(default=30, help_text='Días sugeridos entre visitas. Usado para identificar clientes inactivos. Si es 0, usa la configuración global.', verbose_name='Frecuencia de retorno sugerida (días)')),
                ('duracion_minutos', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
    ]
