# Generated by Django 5.2.8 on 2026-03-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicio',
            name='descuento_fidelizacion_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo de descuento para campañas de fidelización. Si es mayor a 0, tendrá prioridad sobre el porcentaje.', max_digits=10, verbose_name='Descuento de fidelización ($)'),
        ),
        migrations.AddField(
            model_name='historicalservicio',
            name='descuento_fidelizacion_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento específico para este servicio en campañas de fidelización. Si es 0, se usará el porcentaje global de configuración.', max_digits=5, verbose_name='Descuento de fidelización (%)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descuento_fidelizacion_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo de descuento para campañas de fidelización. Si es mayor a 0, tendrá prioridad sobre el porcentaje.', max_digits=10, verbose_name='Descuento de fidelización ($)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descuento_fidelizacion_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento específico para este servicio en campañas de fidelización. Si es 0, se usará el porcentaje global de configuración.', max_digits=5, verbose_name='Descuento de fidelización (%)'),
        ),
    ]
