# Generated by Django 5.2.8 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0003_historicalservicio_descuento_fidelizacion_monto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservicio",
            name="horas_minimas_credito_cancelacion",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Cantidad mínima de horas de anticipación para generar crédito al cancelar. No puede ser menor a 24 horas.",
                verbose_name="Horas mínimas para crédito por cancelación",
            ),
        ),
        migrations.AddField(
            model_name="historicalservicio",
            name="porcentaje_devolucion_sena",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Porcentaje de la seña pagada que se acredita al cancelar en término.",
                max_digits=5,
                verbose_name="Devolución sobre seña (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalservicio",
            name="porcentaje_devolucion_servicio_completo",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Porcentaje del valor total del servicio que se acredita cuando el cliente ya pagó el servicio completo.",
                max_digits=5,
                verbose_name="Devolución sobre servicio completo (%)",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="horas_minimas_credito_cancelacion",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Cantidad mínima de horas de anticipación para generar crédito al cancelar. No puede ser menor a 24 horas.",
                verbose_name="Horas mínimas para crédito por cancelación",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="porcentaje_devolucion_sena",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Porcentaje de la seña pagada que se acredita al cancelar en término.",
                max_digits=5,
                verbose_name="Devolución sobre seña (%)",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="porcentaje_devolucion_servicio_completo",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                help_text="Porcentaje del valor total del servicio que se acredita cuando el cliente ya pagó el servicio completo.",
                max_digits=5,
                verbose_name="Devolución sobre servicio completo (%)",
            ),
        ),
    ]
