# Generated by Django 5.2.8 on 2026-02-07 23:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_automatizacion_reacomodamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServicio',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('descuento_reasignacion', models.DecimalField(decimal_places=2, default=0, help_text='Descuento fijo a aplicar cuando se ofrece un adelanto de turno', max_digits=10, verbose_name='Descuento por reasignación')),
                ('permite_reacomodamiento', models.BooleanField(default=False, help_text='Indica si el servicio participa en la lógica de rellenar huecos', verbose_name='Permite reacomodamiento')),
                ('tipo_descuento_adelanto', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto fijo')], default='PORCENTAJE', max_length=20, verbose_name='Tipo de descuento por adelanto')),
                ('valor_descuento_adelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor del descuento por adelanto')),
                ('tiempo_espera_respuesta', models.PositiveIntegerField(default=15, help_text='Minutos que el sistema espera antes de pasar al siguiente cliente', verbose_name='Tiempo de espera de respuesta (minutos)')),
                ('porcentaje_sena', models.DecimalField(decimal_places=2, default=25.0, help_text='Porcentaje que se cobrará por Mercado Pago', max_digits=5, verbose_name='Porcentaje de seña')),
                ('duracion_minutos', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='servicios.categoriaservicio', verbose_name='Categoría')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Servicio',
                'verbose_name_plural': 'historical Servicios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
