# Generated by Django 5.2.8 on 2026-03-18 19:50

from decimal import Decimal
from django.db import migrations, models


def _backfill_monto_sena_fijo(apps, schema_editor):
    Servicio = apps.get_model("servicios", "Servicio")

    for servicio in Servicio.objects.all().iterator():
        precio = Decimal(servicio.precio or 0)
        monto_sena_fijo = (
            (precio / Decimal("2")).quantize(Decimal("0.01"))
            if precio > 0
            else Decimal("0.00")
        )

        servicio.monto_sena_fijo = monto_sena_fijo
        servicio.porcentaje_sena = Decimal("50.00") if precio > 0 else Decimal("0.00")
        servicio.save(update_fields=["monto_sena_fijo", "porcentaje_sena"])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("servicios", "0004_servicio_credito_cancelacion_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservicio",
            name="bono_reacomodamiento_pago_completo",
            field=models.DecimalField(
                decimal_places=2,
                default=2000,
                help_text="Monto fijo de bono para clientes que pagaron el servicio completo.",
                max_digits=10,
                verbose_name="Bono reacomodamiento (cliente con pago completo)",
            ),
        ),
        migrations.AddField(
            model_name="historicalservicio",
            name="bono_reacomodamiento_senia",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                help_text="Monto fijo de bono para clientes que pagaron seña.",
                max_digits=10,
                verbose_name="Bono reacomodamiento (cliente con seña)",
            ),
        ),
        migrations.AddField(
            model_name="historicalservicio",
            name="monto_sena_fijo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto fijo que se cobra como seña. Se normaliza a la mitad del precio del servicio.",
                max_digits=10,
                verbose_name="Monto fijo de seña",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="bono_reacomodamiento_pago_completo",
            field=models.DecimalField(
                decimal_places=2,
                default=2000,
                help_text="Monto fijo de bono para clientes que pagaron el servicio completo.",
                max_digits=10,
                verbose_name="Bono reacomodamiento (cliente con pago completo)",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="bono_reacomodamiento_senia",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                help_text="Monto fijo de bono para clientes que pagaron seña.",
                max_digits=10,
                verbose_name="Bono reacomodamiento (cliente con seña)",
            ),
        ),
        migrations.AddField(
            model_name="servicio",
            name="monto_sena_fijo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto fijo que se cobra como seña. Se normaliza a la mitad del precio del servicio.",
                max_digits=10,
                verbose_name="Monto fijo de seña",
            ),
        ),
        migrations.RunPython(_backfill_monto_sena_fijo, _noop_reverse),
    ]
