# Generated by Django 5.2.8 on 2026-02-23 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_historicalsala_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsala',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoriaservicio',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='servicios.sala', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='historicalsala',
            name='capacidad_simultanea',
            field=models.PositiveIntegerField(default=1, verbose_name='Capacidad simultánea'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidad_simultanea',
            field=models.PositiveIntegerField(default=1, verbose_name='Capacidad simultánea'),
        ),
    ]
