# Generated by Django 5.2.8 on 2026-02-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_remove_historicalsala_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicio',
            name='frecuencia_recurrencia_dias',
            field=models.PositiveIntegerField(default=30, help_text='Días sugeridos entre visitas. Usado para identificar clientes inactivos. Si es 0, usa la configuración global.', verbose_name='Frecuencia de retorno sugerida (días)'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='frecuencia_recurrencia_dias',
            field=models.PositiveIntegerField(default=30, help_text='Días sugeridos entre visitas. Usado para identificar clientes inactivos. Si es 0, usa la configuración global.', verbose_name='Frecuencia de retorno sugerida (días)'),
        ),
    ]
