# Generated by Django 5.2.8 on 2026-03-03 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_billetera_movimientobilletera'),
        ('turnos', '0006_historicalturno_sala_turno_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoMercadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(max_length=255, verbose_name='ID de Preferencia MP')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de Pago MP')),
                ('init_point', models.URLField(blank=True, max_length=512, verbose_name='URL de Checkout')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('authorized', 'Autorizado'), ('in_process', 'En proceso'), ('in_mediation', 'En mediación'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('charged_back', 'Contracargo')], default='pending', max_length=20, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_mercadopago', to='clientes.cliente', verbose_name='Cliente')),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_mercadopago', to='turnos.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Pago Mercado Pago',
                'verbose_name_plural': 'Pagos Mercado Pago',
                'ordering': ['-creado_en'],
            },
        ),
    ]
