# Generated by Django 5.2.8 on 2026-03-13 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mercadopago', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomercadopago',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago_mercadopago', to='turnos.turno', verbose_name='Turno'),
        ),
    ]
