# Generated by Django 5.2.8 on 2026-03-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomercadopago',
            name='moneda',
            field=models.CharField(default='ARS', max_length=10, verbose_name='Moneda'),
        ),
    ]
