# Generated by Django 5.2.8 on 2026-04-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_billetera_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Telegram Update Log',
                'verbose_name_plural': 'Telegram Update Logs',
            },
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('phone_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_links', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Telegram Link',
                'verbose_name_plural': 'Telegram Links',
            },
        ),
        migrations.CreateModel(
            name='TelegramConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('confirm_cancel', 'Confirm Cancel')], default='idle', max_length=32)),
                ('pending_turno_id', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='telegram_bot.telegramlink')),
            ],
            options={
                'verbose_name': 'Telegram Conversation State',
                'verbose_name_plural': 'Telegram Conversation States',
            },
        ),
    ]
