# Generated by Django 5.2.8 on 2026-06-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_conversation_state_cancel_reason_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramconversationstate',
            name='pending_payload',
        ),
        migrations.AlterField(
            model_name='telegramconversationstate',
            name='state',
            field=models.CharField(choices=[('idle', 'Idle'), ('confirm_cancel', 'Confirm Cancel'), ('ended', 'Ended')], default='idle', max_length=32),
        ),
    ]
