# Generated by Django 5.2.8 on 2026-01-24 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('horario_entrada', models.TimeField(verbose_name='Hora de entrada')),
                ('horario_salida', models.TimeField(verbose_name='Hora de salida')),
                ('dias_trabajo', models.CharField(help_text='Días de la semana (ej: L,M,M,J,V)', max_length=20, verbose_name='Días de trabajo')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión (%)')),
                ('is_disponible', models.BooleanField(default=True, verbose_name='Disponible para turnos')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía profesional')),
                ('promedio_calificacion', models.DecimalField(decimal_places=2, default=5.0, help_text='Promedio de todas las encuestas recibidas (0-10)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Promedio de calificación')),
                ('total_encuestas', models.PositiveIntegerField(default=0, help_text='Número total de encuestas respondidas', verbose_name='Total de encuestas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_experiencia', models.IntegerField(choices=[(1, 'Principiante'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], default=2, verbose_name='Nivel de experiencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio de Profesional',
                'verbose_name_plural': 'Servicios de Profesionales',
            },
        ),
        migrations.CreateModel(
            name='HorarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Horario de Profesional',
                'verbose_name_plural': 'Horarios de Profesionales',
                'ordering': ['empleado', 'dia_semana', 'hora_inicio'],
            },
        ),
    ]
