# Generated by Django 4.2.16 on 2025-09-23 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidades', models.CharField(choices=[('corte', 'Especialista en Corte'), ('color', 'Colorista'), ('tratamientos', 'Especialista en Tratamientos'), ('unas', 'Manicurista/Pedicurista'), ('maquillaje', 'Maquillador/a'), ('general', 'Generalista')], max_length=20, verbose_name='Especialidad principal')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('horario_entrada', models.TimeField(verbose_name='Hora de entrada')),
                ('horario_salida', models.TimeField(verbose_name='Hora de salida')),
                ('dias_trabajo', models.CharField(help_text='Días de la semana (ej: L,M,M,J,V)', max_length=20, verbose_name='Días de trabajo')),
                ('comision_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión (%)')),
                ('is_disponible', models.BooleanField(default=True, verbose_name='Disponible para turnos')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía profesional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='EmpleadoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_experiencia', models.IntegerField(choices=[(1, 'Principiante'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_disponibles', to='empleados.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_disponibles', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio de Empleado',
                'verbose_name_plural': 'Servicios de Empleados',
            },
        ),
    ]
