# Generated by Django 5.2.8 on 2026-01-24 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='empleadoservicio',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_disponibles', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='empleadoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales_disponibles', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='horarioempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_detallados', to='empleados.empleado', verbose_name='Profesional'),
        ),
        migrations.AlterUniqueTogether(
            name='empleadoservicio',
            unique_together={('empleado', 'servicio')},
        ),
        migrations.AlterUniqueTogether(
            name='horarioempleado',
            unique_together={('empleado', 'dia_semana', 'hora_inicio')},
        ),
    ]
