# Generated by Django 5.2.8 on 2026-03-17 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_remove_rating_fields'),
        ('servicios', '0003_historicalservicio_descuento_fidelizacion_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='empleadoservicio',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_disponibles', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='empleadoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales_disponibles', to='servicios.servicio', verbose_name='Servicio'),
        ),
    ]
