# Generated by Django 4.2.16 on 2025-11-03 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicios', '0001_initial'),
        ('empleados', '0003_horarioempleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterModelOptions(
            name='empleadoservicio',
            options={'verbose_name': 'Servicio de Profesional', 'verbose_name_plural': 'Servicios de Profesionales'},
        ),
        migrations.AlterModelOptions(
            name='horarioempleado',
            options={'ordering': ['empleado', 'dia_semana', 'hora_inicio'], 'verbose_name': 'Horario de Profesional', 'verbose_name_plural': 'Horarios de Profesionales'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='empleadoservicio',
            name='nivel_experiencia',
            field=models.IntegerField(choices=[(1, 'Principiante'), (2, 'Intermedio'), (3, 'Avanzado'), (4, 'Experto')], default=2, verbose_name='Nivel de experiencia'),
        ),
        migrations.AlterField(
            model_name='empleadoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales_disponibles', to='servicios.servicio', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='horarioempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_detallados', to='empleados.empleado', verbose_name='Profesional'),
        ),
    ]
