# Generated by Django 5.2.7 on 2025-11-20 04:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='promedio_calificacion',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Promedio de todas las encuestas recibidas (0-10)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Promedio de calificación'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='total_encuestas',
            field=models.PositiveIntegerField(default=0, help_text='Número total de encuestas respondidas', verbose_name='Total de encuestas'),
        ),
    ]
