# Generated by Django 5.2.7 on 2025-12-02 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_promedio_calificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='especialidades',
        ),
    ]
