# Generated by Django 4.2.16 on 2025-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('preferencias', models.TextField(blank=True, null=True, verbose_name='Preferencias y notas')),
                ('fecha_primera_visita', models.DateTimeField(blank=True, null=True, verbose_name='Primera visita')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Cliente VIP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
