# Generated by Django 5.2.8 on 2026-03-13 02:17

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('preferencias', models.TextField(blank=True, null=True, verbose_name='Preferencias y notas')),
                ('fecha_primera_visita', models.DateTimeField(blank=True, null=True, verbose_name='Primera visita')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Cliente VIP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('preferencias', models.TextField(blank=True, null=True, verbose_name='Preferencias y notas')),
                ('fecha_primera_visita', models.DateTimeField(blank=True, null=True, verbose_name='Primera visita')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Cliente VIP')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de actualización')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=20, verbose_name='Tipo de movimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo anterior')),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo nuevo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento de Billetera',
                'verbose_name_plural': 'Movimientos de Billetera',
                'ordering': ['-created_at'],
            },
        ),
    ]
