# Generated by Django 5.2.8 on 2026-03-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_is_active_historicalcliente_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='billetera',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha límite hasta la cual el crédito de la billetera es válido.', null=True, verbose_name='Fecha de vencimiento del saldo'),
        ),
    ]
