# Generated by Django 5.2.8 on 2026-02-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_historicalcliente'),
        ('turnos', '0006_historicalturno_sala_turno_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billetera', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=20, verbose_name='Tipo de movimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo anterior')),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo nuevo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('billetera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='clientes.billetera', verbose_name='Billetera')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_billetera', to='turnos.turno', verbose_name='Turno relacionado')),
            ],
            options={
                'verbose_name': 'Movimiento de Billetera',
                'verbose_name_plural': 'Movimientos de Billetera',
                'ordering': ['-created_at'],
            },
        ),
    ]
