# Generated by Django 5.2.7 on 2025-11-17 07:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0006_remove_turno_fecha_hora_cancelado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField(blank=True, help_text='Puntaje de 0 a 10', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puntaje')),
                ('descargo_texto', models.TextField(blank=True, help_text='Comentario adicional del cliente', null=True, verbose_name='Comentario')),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Fecha y hora en que se respondió la encuesta', null=True, verbose_name='Fecha de Respuesta')),
                ('clasificacion', models.CharField(blank=True, choices=[('P', 'Promotor'), ('R', 'Pasivo'), ('N', 'Detractor')], help_text='Clasificación automática basada en el puntaje', max_length=1, null=True, verbose_name='Clasificación NPS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('turno', models.OneToOneField(help_text='Turno asociado a esta encuesta', on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='turnos.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-created_at'],
            },
        ),
    ]
