# Generated by Django 5.2.8 on 2026-01-24 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, default=5.0, help_text='Promedio de las 10 preguntas (calculado automáticamente)', max_digits=4)),
                ('clasificacion', models.CharField(blank=True, choices=[('N', 'Negativa'), ('Ne', 'Neutral'), ('P', 'Positiva')], default='Ne', help_text='Clasificación automática según puntaje promedio', max_length=2)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encuesta de Satisfacción',
                'verbose_name_plural': 'Encuestas de Satisfacción',
                'ordering': ['-fecha_respuesta'],
            },
        ),
        migrations.CreateModel(
            name='EncuestaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_negativa', models.PositiveSmallIntegerField(default=4, help_text="Puntaje máximo para clasificar como 'Negativa' (<=)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('umbral_neutral_min', models.PositiveSmallIntegerField(default=5, help_text="Puntaje mínimo para clasificar como 'Neutral'", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('umbral_neutral_max', models.PositiveSmallIntegerField(default=7, help_text="Puntaje máximo para clasificar como 'Neutral' (<=)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('umbral_notificacion_propietario', models.PositiveSmallIntegerField(default=3, help_text='Número de encuestas negativas en 30 días que disparan alerta al propietario', validators=[django.core.validators.MinValueValidator(1)])),
                ('dias_ventana_alerta', models.PositiveSmallIntegerField(default=30, help_text='Días hacia atrás para contar encuestas negativas', validators=[django.core.validators.MinValueValidator(1)])),
                ('email_override_debug', models.EmailField(default='gimenezivanb@gmail.com', help_text='Email que recibe todas las notificaciones cuando DEBUG=True', max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Encuestas',
                'verbose_name_plural': 'Configuración de Encuestas',
            },
        ),
        migrations.CreateModel(
            name='EncuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Pregunta que se mostrará al cliente', max_length=255, verbose_name='Texto de la pregunta')),
                ('puntaje_maximo', models.PositiveSmallIntegerField(default=10, help_text='Máximo puntaje que puede asignar el cliente (ej: 10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntaje máximo')),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Orden en el que aparece en el formulario', verbose_name='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa se muestra en las encuestas nuevas', verbose_name='Activa')),
                ('categoria', models.CharField(blank=True, help_text='Categoría de la pregunta (ej: Servicio, Atención, Instalaciones)', max_length=50, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta de Encuesta',
                'verbose_name_plural': 'Preguntas de Encuesta',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_valor', models.PositiveSmallIntegerField(help_text='Puntaje asignado por el cliente (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Valor de la respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Respuesta de Cliente',
                'verbose_name_plural': 'Respuestas de Clientes',
            },
        ),
    ]
