# Generated by Django 5.2.7 on 2025-11-20 04:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_user'),
        ('empleados', '0005_empleado_promedio_calificacion_and_more'),
        ('encuestas', '0001_initial'),
        ('turnos', '0008_alter_turno_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral_negativa', models.PositiveSmallIntegerField(default=4, help_text="Puntaje máximo para clasificar como 'Negativa' (<=)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('umbral_neutral_min', models.PositiveSmallIntegerField(default=5, help_text="Puntaje mínimo para clasificar como 'Neutral'", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('umbral_neutral_max', models.PositiveSmallIntegerField(default=7, help_text="Puntaje máximo para clasificar como 'Neutral' (<=)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('umbral_notificacion_propietario', models.PositiveSmallIntegerField(default=3, help_text='Número de encuestas negativas en 30 días que disparan alerta al propietario', validators=[django.core.validators.MinValueValidator(1)])),
                ('dias_ventana_alerta', models.PositiveSmallIntegerField(default=30, help_text='Días hacia atrás para contar encuestas negativas', validators=[django.core.validators.MinValueValidator(1)])),
                ('email_override_debug', models.EmailField(default='gimenezivanb@gmail.com', help_text='Email que recibe todas las notificaciones cuando DEBUG=True', max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Encuestas',
                'verbose_name_plural': 'Configuración de Encuestas',
            },
        ),
        migrations.AlterModelOptions(
            name='encuesta',
            options={'ordering': ['-fecha_respuesta'], 'verbose_name': 'Encuesta de Satisfacción', 'verbose_name_plural': 'Encuestas de Satisfacción'},
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='descargo_texto',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='alerta_enviada',
            field=models.BooleanField(default=False, help_text='Indica si se envió alerta al propietario'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentarios adicionales del cliente', null=True),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='empleados.empleado', verbose_name='Profesional evaluado'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='procesada',
            field=models.BooleanField(default=False, help_text='Indica si ya se procesó para ranking y alertas'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('N', 'Negativa'), ('Ne', 'Neutral'), ('P', 'Positiva')], default='Ne', help_text='Clasificación automática según puntaje', max_length=2),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_respuesta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='puntaje',
            field=models.PositiveSmallIntegerField(default=5, help_text='Puntaje de 0 a 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='turnos.turno', verbose_name='Turno asociado'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='encuesta',
            index=models.Index(fields=['empleado', 'clasificacion', 'fecha_respuesta'], name='encuestas_e_emplead_117d35_idx'),
        ),
        migrations.AddIndex(
            model_name='encuesta',
            index=models.Index(fields=['cliente', 'fecha_respuesta'], name='encuestas_e_cliente_049664_idx'),
        ),
    ]
