# Generated by Django 5.2.8 on 2026-01-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encuestas', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='turnos.turno', verbose_name='Turno asociado'),
        ),
        migrations.AddIndex(
            model_name='encuestapregunta',
            index=models.Index(fields=['is_active', 'orden'], name='encuestas_e_is_acti_b380a2_idx'),
        ),
        migrations.AddField(
            model_name='respuestacliente',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.encuesta', verbose_name='Encuesta'),
        ),
        migrations.AddField(
            model_name='respuestacliente',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='encuestas.encuestapregunta', verbose_name='Pregunta'),
        ),
        migrations.AddIndex(
            model_name='encuesta',
            index=models.Index(fields=['turno', 'clasificacion', 'fecha_respuesta'], name='encuestas_e_turno_i_dd5725_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestacliente',
            index=models.Index(fields=['encuesta', 'pregunta'], name='encuestas_r_encuest_ce4c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='respuestacliente',
            index=models.Index(fields=['pregunta', 'respuesta_valor'], name='encuestas_r_pregunt_a4147b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestacliente',
            unique_together={('encuesta', 'pregunta')},
        ),
    ]
