# Generated by Django 5.2.7 on 2025-11-20 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_encuestaconfig_alter_encuesta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='pregunta10_recomendacion',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿Qué tan probable es que recomiendes este servicio?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta1_calidad_servicio',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿Qué tan satisfecho estás con la calidad del servicio?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta2_profesionalismo',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿Cómo calificarías el profesionalismo del especialista?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta3_puntualidad',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿El servicio comenzó a tiempo?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta4_limpieza',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿Cómo calificarías la limpieza e higiene del lugar?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta5_atencion',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿Cómo fue la atención recibida?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta6_resultado',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿Estás satisfecho con el resultado final?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta7_precio',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿Consideras que el precio es justo?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta8_comodidad',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿Te sentiste cómodo durante el servicio?'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='pregunta9_comunicacion',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='¿El especialista te explicó claramente el proceso?'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('N', 'Negativa'), ('Ne', 'Neutral'), ('P', 'Positiva')], default='Ne', help_text='Clasificación automática según puntaje promedio', max_length=2),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Promedio de las 10 preguntas (calculado automáticamente)', max_digits=4),
        ),
    ]
