# Generated by Django 5.2.7 on 2025-11-20 14:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_encuesta_pregunta10_recomendacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Pregunta que se mostrará al cliente', max_length=255, verbose_name='Texto de la pregunta')),
                ('puntaje_maximo', models.PositiveSmallIntegerField(default=10, help_text='Máximo puntaje que puede asignar el cliente (ej: 10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Puntaje máximo')),
                ('orden', models.PositiveSmallIntegerField(default=1, help_text='Orden en el que aparece en el formulario', verbose_name='Orden de aparición')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa se muestra en las encuestas nuevas', verbose_name='Activa')),
                ('categoria', models.CharField(blank=True, help_text='Categoría de la pregunta (ej: Servicio, Atención, Instalaciones)', max_length=50, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta de Encuesta',
                'verbose_name_plural': 'Preguntas de Encuesta',
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['is_active', 'orden'], name='encuestas_e_is_acti_b380a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_valor', models.PositiveSmallIntegerField(help_text='Puntaje asignado por el cliente (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Valor de la respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.encuesta', verbose_name='Encuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='encuestas.encuestapregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Cliente',
                'verbose_name_plural': 'Respuestas de Clientes',
                'indexes': [models.Index(fields=['encuesta', 'pregunta'], name='encuestas_r_encuest_ce4c7c_idx'), models.Index(fields=['pregunta', 'respuesta_valor'], name='encuestas_r_pregunt_a4147b_idx')],
                'unique_together': {('encuesta', 'pregunta')},
            },
        ),
    ]
