# Generated by Django 5.2.7 on 2025-12-02 00:02

from django.db import migrations, models


def migrate_encuesta_table(apps, schema_editor):
    """Migración manual para SQLite - recrear tabla sin campos obsoletos"""
    with schema_editor.connection.cursor() as cursor:
        # 1. Crear nueva tabla temporal con estructura actualizada
        cursor.execute("""
            CREATE TABLE "encuestas_encuesta_new" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "turno_id" bigint NOT NULL UNIQUE REFERENCES "turnos_turno" ("id") DEFERRABLE INITIALLY DEFERRED,
                "puntaje" real NOT NULL,
                "clasificacion" varchar(2) NOT NULL,
                "fecha_respuesta" datetime NOT NULL,
                "created_at" datetime NOT NULL,
                "updated_at" datetime NOT NULL
            );
        """)
        
        # 2. Copiar datos de tabla vieja a nueva (solo campos que se mantienen)
        cursor.execute("""
            INSERT INTO encuestas_encuesta_new 
                (id, turno_id, puntaje, clasificacion, fecha_respuesta, created_at, updated_at)
            SELECT 
                id, turno_id, puntaje, clasificacion, fecha_respuesta, created_at, updated_at
            FROM encuestas_encuesta;
        """)
        
        # 3. Eliminar tabla vieja
        cursor.execute("DROP TABLE encuestas_encuesta;")
        
        # 4. Renombrar nueva tabla
        cursor.execute("ALTER TABLE encuestas_encuesta_new RENAME TO encuestas_encuesta;")
        
        # 5. Crear nuevo índice
        cursor.execute("""
            CREATE INDEX "encuestas_e_turno_i_dd5725_idx" 
            ON "encuestas_encuesta" ("turno_id", "clasificacion", "fecha_respuesta");
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_encuestapregunta_respuestacliente'),
        ('turnos', '0008_alter_turno_unique_together'),
    ]

    operations = [
        migrations.RunPython(migrate_encuesta_table, migrations.RunPython.noop),
    ]
